### ISSUE TITLE
vignette is missing

### ISSUE THREAD

**Issue by silberzwiebel** [jashubbard/itrackR#1]
Thanks for this package, great work!

In the README is written that there is not much documentation yet but a vignette should be readable from `vignette('itrackR')`
I installed `itrackR` on a Mac and a linux machine but there is no vignette (I know, I can look at it here on github, but just to let you know...)

**Comment by silberzwiebel** [comment]
Okay, I figured it out. Apparently, I missed the package `knitr`and `rmarkdown`(and maybe also `roxygen2`). I've installed those and now the vignette works. Could you add these packages to the automatically installed dependencies?

**Comment by jashubbard** [comment]
Done! Thanks for narrowing it down, this was causing some headaches.
