### ISSUE TITLE
get_sample_epochs for pupil data recorded at 500 Hz

### ISSUE THREAD

**Issue by garvin2506** [jashubbard/itrackR#10]
Hi again,

when I run get_sample_epochs on my data (acquired at 500 Hz), I'm getting these curious pupil results:

| ID | ResultsCategory | timepoint | pupil | epoch_time |
| --: | --: | --: | --: | --: |
| 3207 | 1 | 1 | 6241.857 | -500 |
| 3207 | 1 | 2 | 5853.600 | -499 |
| 3207 | 1 | 3 | 6242.214 | -498 |
| 3207 | 1 | 4 | 5854.000 | -497 |
| 3207 | 1 | 5 | 6242.571 | -496 |
| 3207 | 1 | 6 | 5854.400 | -495 |
| 3207 | 1 | 7 | 6243.357 | -494 |
| 3207 | 1 | 8 | 5854.200 | -493 |
| 3207 | 1 | 9 | 6243.786 | -492 |
| 3207 | 1 | 10 | 5854.800 | -491 |

It looks like a clean odd-even split of the pupil data! :)
Do you have any idea why this is the case? To me it looks like a sampling rate issue.

Any ideas would be greatly appreciated!

**Comment by jashubbard** [comment]
hmm. Would you mind posting the code you used and sharing 1 edf and the behavioral file? I suspect it has to do with the sampling rate since I develop the code with 1000 hz files (although in principle it should work the same with 500).

**Comment by garvin2506** [comment]
sure, below are the commands and attached please find the two files:

z <- itrackr(edfs)
beh <- read.table('$/3207_pre.txt', 
                     header=TRUE, sep="\t", na.strings="NA", dec=",", fill=TRUE, strip.white=TRUE)
z<- set_index(z,varnames=c('TrialID'), patterns=c('Fixation TrialID[1-84]*'), numeric.only=T)
z <- find_messages(z,varnames=c('Results'), patterns=c('^Results'), timestamp=T)
beh$ID <- 3207
z <- add_behdata(z,beh)
z <- load_samples(z, outdir = data_folder, parallel=T, force=T,ncores = 2)
z <- remove_blinks(z,interpolate = T)
epochs <- get_sample_epochs(z,factors=c('ResultsCategory'), event='Results', epoch = c(-500,300), aggregate=T)

[data.zip](https://github.com/jashubbard/itrackR/files/548480/data.zip)

**Comment by jashubbard** [comment]
Thanks. Took me a while to get to this, but finally got it working. It was indeed related to the sampling rate. The problem was that on some trials, the time relative to the time-locking event was even (2,4,6,8...) and on other trials it was odd (1,3,5...) since each the time increment is 2ms (so the time-locking event would fall on an even or odd timestamp). When aggregating across trials, it ended up with a separate average for the "even" trials and "odd" trials, which were then interleaved. The functions should now be robust to different sampling rates, but let me know if you notice any more problems.

**Comment by garvin2506** [comment]
Thanks a lot, sounds good, but there must be a tiny issue in the updated functions now because I can't update the package:

devtools::install_github('jashubbard/itrackR',build_vignettes = TRUE)
Downloading GitHub repo jashubbard/itrackR@master
from URL https://api.github.com/repos/jashubbard/itrackR/zipball/master
Installing itrackR
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/RcppArmadillo_0.7.500.0.0.tgz'

# Content type 'application/x-gzip' length 1354529 bytes (1.3 MB)

downloaded 1.3 MB

tar: Failed to set default locale
tar: Failed to set default locale
Installing RcppArmadillo
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/private/var/folders/cn/n_zx5lmd71jfrv6vzvtqr3wh0000gn/T/RtmpcyTXqN/devtools6b450caba27/RcppArmadillo'  \
  --library='/Library/Frameworks/R.framework/Versions/3.3/Resources/library' --install-tests 
- installing _binary_ package 'RcppArmadillo' ...
- DONE (RcppArmadillo)
  '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD build  \
  '/private/var/folders/cn/n_zx5lmd71jfrv6vzvtqr3wh0000gn/T/RtmpcyTXqN/devtools6b47c23875/jashubbard-itrackR-5ebbd57'  \
  --no-resave-data --no-manual 

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
- checking for file '/private/var/folders/cn/n_zx5lmd71jfrv6vzvtqr3wh0000gn/T/RtmpcyTXqN/devtools6b47c23875/jashubbard-itrackR-5ebbd57/DESCRIPTION' ... OK
- preparing 'itrackR':
- checking DESCRIPTION meta-information ... OK
- cleaning src
- installing the package to build vignettes
- creating vignettes ... ERROR
  During startup - Warning messages:
  1: Setting LC_CTYPE failed, using "C" 
  2: Setting LC_TIME failed, using "C" 
  3: Setting LC_MESSAGES failed, using "C" 
  4: Setting LC_MONETARY failed, using "C" 
  Loading required package: RcppArmadillo
  Quitting from lines 202-203 (itrackR.Rmd) 
  Error: processing vignette 'itrackR.Rmd' failed with diagnostics:
  replacement has 12270 rows, data has 0
  Execution halted
  Error: Command failed (1)

**Comment by jashubbard** [comment]
Sorry, that was an issue that crept up from another fix. Now it should work.

**Comment by garvin2506** [comment]
I'm afraid that there is another small issue now, right when loading in the edfs it throws an error:

z <- itrackr(edfs)
Error in .Call("get_trial_data", EDFfile, event.fields, sample.fields,  : 
  "get_trial_data" not resolved from current namespace (edfR)

**Comment by jashubbard** [comment]
That's odd, seems like an issue for the other package (edfR) which I haven't changed recently. First try closing and re-openning R, then try reinstalling edfR manually `devtools::install_github('jashubbard/edfR')`

**Comment by garvin2506** [comment]
had to restart my macbook completely, but now it works, thanks a lot!
