### ISSUE TITLE
Error in UseMethod("left_join") during drift correction

### ISSUE THREAD

**Issue by fusaroli** [jashubbard/itrackR#7]
I am following the vignette and applying it to my data. All works well til I get to drift correction.
When I type
drift_correct(z)
(or the same with any attribute)
I get:

Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "function"

Here my data:
https://www.dropbox.com/s/0w8i3fha10fvwqk/trial.RData?dl=0

**Comment by jashubbard** [comment]
Looks like the problem is that you haven't added the behavioral data yet (using `add_behdata`). You should also update itrackR. I've fixed a couple bugs that led to this error.

**Comment by fusaroli** [comment]
Thanks for the answer!

I actually tried that, by doing:

```
#find messages to use as our index variables (to merge with our behavioral data)
z<- set_index(z,varnames=c('Trial'), patterns=c('^TRIALID [0-9]*'), numeric.only=T)

#find messages that specify the onset of events, extract the timestamps
z <- find_messages(z,varnames=c("fixation_start","subject_rating_start","subject_rating_start","grp_emphasis_start"), patterns=c("fixation_start","subject_rating_start","subject_rating_start","grp_emphasis_start"), timestamp=T)

z <- add_behdata(z,beh,append=F)
```

But I keep getting 

> Error in merge(beh, eyedata, by = c("ID", obj$indexvars), all.x = T) : 
>   object 'beh' not found

Same results now after updating the package.
Sorry for the bother, but I couldn't find a solution.

**Comment by jashubbard** [comment]
So `beh` is a data frame that you provide, which is the behavioral data that goes along with your experiment. Did you load that? It should have a variable "ID" for the subject ID, and a variable "Trial" (or whatever you specify in `set_index`). For the moment the package is built around requiring this. If you don't actually need it, you could make a dummy data frame using something like `beh<- expand.grid(ID=101:105, Trial=1:100)` .

`drift_correct` is optional, and if you plot your data and everything lines up well, you can skip it. If you do use it, by default it will perform drift correction for each subject ("ID"), but you can also provide other behavioral variables, and it will perform the correction separately for each unique value of those (within each subject). For example, if `beh` contained a variable "Block", you could perform the correction separately for each block and subject.

**Comment by fusaroli** [comment]
Thanks. That did it. I really appreciate the help!
