### ISSUE TITLE
read in and merge pupil data?

### ISSUE THREAD

**Issue by garvin2506** [jashubbard/itrackR#8]
Hi,

great stuff!
I would like to read in and merge pupil data in the same way as the fixation data (except that there will be many more rows per trial of course) using itrackR. Is there currently any way to get the pupil column read in and merged with behavioral data?

That would be fantastic!

**Comment by jashubbard** [comment]
Thanks! Yes, it's designed to work with pupil data too. At the moment it is not as thoroughly developed as the fixation workflow, mostly because my own projects have been fixation-focused lately (although I'm jumping back into pupil data again in the very near future). The initial workflow of loading the edfs, finding the index variables, and merging with behavioral data is the same as in the vignette. To add with the pupil data, you just need to add these lines: 

```
#pupil data is saved on the hard drive as .rds files
#if you don't specify this folder, they're saved in a temporary folder
data_folder <- 'path/to/some/folder'

#load the samples for each subject
#store as .rds files for each subject in data_folder
#increase ncores if you have more cores and want to load more in parallel
z <- load_samples(z, outdir = data_folder, parallel=T, force=T,ncores = 2)

#remove blinks
#do interpolate=F if you want the blinks to stay as missing data (NA)
z <- remove_blinks(z,interpolate = T)

#optional - visualize all the pupil data for 1 subject
#use bin=TRUE to break the data into 10 bins to visualize easier. 
#you can do this before and after remove_blinks to gague the effectiveness
plot.samples(z,ID=104, bin=T)

#create epochs of pupil data relative to some event (STIMONSET)
#starting from -2000 samples to 2000 samples after
#NOTE: it's number of *samples*. If you're recording at 1000Hz this is the same as milliseconds, 
#but if you're at a slower rate it's not. 
z <- epoch_samples(z,'STIMONSET',epoch=c(-2000,2000),field='pa')

#merge epoched pupil data with behavioral and put into a data frame
#if you want to plot with ggplot, it's more convenient for shape='long'
#if you want to baseline for each trial, you can specify an epoch (in samples) to serve as the baseline period. 
#This is NOT relative to the time-locking event, just relative to the start of your epoch. 
#So, to use the first 100 samples as the baseline, use c(1,100)
allepochs <- get_all_epochs(z,'STIMONSET',shape='wide',baseline=NULL,beh=T)
allepochs <- dplyr::arrange(allepochs,ID,Block,Set,Trial)

#optional
#get mean from 100-200 ms post-stimulus for each trial
allepochs$mean_pupil <- rowMeans(select(allepochs,t100:t200),na.rm=T)
```

These functions will be updated (and documented) in the near future. So stay tuned.

**Comment by jashubbard** [comment]
I just made a significant update to the pupil-related code and included a vignette. Some of the code above won't work. Just do: `devtools::install_github('jashubbard/itrackR',build_vignettes = TRUE)` then `vignette('itrackR_pupils')`for an example.
