### ISSUE TITLE
add_behdata for one subject only

### ISSUE THREAD

**Issue by garvin2506** [jashubbard/itrackR#9]
If I want to look at one subject's data only (unlike in the vignette), add_behdata() gives out this: 
Error in fix.by(by.x, x) : 'by' must specify a uniquely valid column

The source of the error seems to be the preset argument "ID" in
behmerged <- merge(beh, eyedata, by = c("ID", obj$indexvars), 
                all.x = T)

Changing this line to
behmerged <- merge(beh, eyedata, by = c(obj$indexvars), 
                all.x = T)
apparently solves the issue (the merging looks fine now), but permanently changing this value doesn't seem to be a great idea.

Any thoughts on this?

Thanks again for your great work!

**Comment by jashubbard** [comment]
I need to add a note to the vignette, but the workflow depends on there being an "ID" column in the behavioral file that matches the ID number extracted from the edf file name. At the moment, it extracts only numbers from the name (so "sub_104.edf" becomes 104). Before merging, you could just do `beh$ID <- 104` and that should fix it. If you're unsure what the IDs are, you can check the value of `obj$subs`. I'm working on making this a bit more flexible in the future.

**Comment by garvin2506** [comment]
Thanks, that makes a lot of sense and works perfectly!
